[Doc] EZP-27326: Use Nameable interface instead of deprecated getName function
ezsystems/TweetFieldTypeBundle pull request #27
Opened 2017-07-20 11:43 UTC by natanael89

Documentation changes reflecting code changes from #26.

> JIRA : [EZP-27326](https://jira.ez.no/browse/EZP-27326)
Currently, Tweet FieldType uses getName() method for Content Items naming. This method is currently marked as deprecated and usage of Nameable interface is suggested instead.
Only a few core Field Types actually use Nameable interface right now, but I took them as examples.
I'm not 100% happy about testing (for example throwing RuntimeException in getName() method), but that's the way it is done in core.

2017-08-01 13:20 UTC, DominikaK approved these changes

2017-09-15 14:26 UTC, mere-teresa requested changes
Approved, except for minor changes asked.

2017-09-15 14:26 UTC, mere-teresa commented on docs/implement_the_tweet_type_class.md
> +The recommended way to allow the field type to be able to generate content name is through implementing the `eZ\Publish\SPI\FieldType\Nameable` interface. It was also used in this tutorial.
First upper case for Field Type (keyword from the domain)

2017-09-15 14:26 UTC, mere-teresa commented on docs/implement_the_tweet_type_class.md
> +In the `eZ\Publish\SPI\FieldType\FieldType` interface there is also `getName()` method that is currently deprecated and replaced by `getFieldName()`. You can leave its body empty or throw an exceptio
What do you recommend? Leave empty or throw Exception?

2017-09-19 08:47 UTC, natanael89 commented
@mere-teresa I have made the changes that you suggested.

2017-10-12 07:52 UTC, merged