[Doc] EZP-27294: Add option to declare list of authors from which the tweets are allowed
ezsystems/TweetFieldTypeBundle pull request #29
Opened 2017-07-21 09:57 UTC by natanael89

Documentation changes reflecting code changes from #28.

>JIRA: [EZP-27294](https://jira.ez.no/browse/EZP-27294)
This PR aims at adding the possibility to declare a list of allowed tweet authors.
This feature currently is signalled throughout the code and in the tutorial documentation but is not implemented fully. My PR adds the missing pieces.

2017-08-01 12:58 UTC, DominikaK requested changes
A few small clarifications in the comments

2017-08-01 12:58 UTC, DominikaK commented on docs/add_a_validation.md
> +We want to add the option to configure list of authors from which the tweets are allowed. To achieve this, we have to:
We want to add the option to configure **a** list of authors **whose** tweets are allowed.

2017-08-01 12:58 UTC, DominikaK commented on docs/add_a_validation.md
> +In addition to validating the URL with a regular expression, which we implemented before, if your Field Type instance’s configuration contains a `TweetValueValidator` key, you will check that the use
A bit longing, I'd rephrase it like this:
Earlier we validated the URL with a regular expression. Now, if your the configuration of your Field Type's instance contains a `TweetValueValidator` key, you will check that the username in the status URL matches one of the valid authors.

2017-08-01 12:58 UTC, DominikaK commented on docs/add_a_validation.md
> +Next, we need to create a way for user to input a list of authors for our validation. To achieve this, we need to implement a FormMapper that allows us to add an input field to form with content fiel
Next, we need to create a way for **the** user to input a list of authors for our validation. To achieve this, we need to implement a FormMapper that allows us to add an input field to **the form where the user defines the fields**.

2017-08-01 12:58 UTC, DominikaK commented on docs/add_a_validation.md
> +
Wouldn't it be better to put the full file here? An over-eager copy-paster (like me) could overlook the first 15 lines and get errors (unless you consider it to be an obvious step for someone who uses this tutorial)

2017-08-01 12:58 UTC, DominikaK commented on docs/add_a_validation.md
> +
same comment as above

2017-08-01 12:58 UTC, DominikaK commented on docs/add_a_validation.md
> +We have the new part of the form defined, but we still need to show it to the user. To do that, we need to create file containing the view:
To do that, we need to create **a** file containing the view:

2017-08-01 12:58 UTC, DominikaK commented on docs/add_a_validation.md
> +You should now be able to configure list of authors when editing Content Type with Tweet Field Type.
You should now be able to configure **a** list of authors when editing **a** Content Type with **the** Tweet Field Type.

2017-08-01 13:33 UTC, natanael89 commented
I have added your fixes. Thanks a lot @DominikaK :)

2017-08-01 13:35 UTC, DominikaK approved these changes

2017-09-19 12:18 UTC, mere-teresa requested changes

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +For a TextLine (length validation), it means checking that both min length and max length are positive integers, and that min is lower than max.
Maybe put a First Uppercase to Min Length et Max Length to reinforce the information that they are Fields? This sentence is very hard to read.

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +When an instance of the type is added to a Content Type, `validateValidatorConfiguration()` receives the configuration for the validators used by the Type as an array. It must return an array of erro
> It must return 

Replace it by the real subject of the sentence, please. We would like to ease the reading.

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +For TextLine, the provided array looks like this:
I propose:

> For the Fieldtype TextLine, the array provided by ... looks like this:

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +The structure of this array is totally free, and up to each type implementation. In this tutorial it will mimic what is done in native Field Types:
> The structure of this array is totally free, and up to each type implementation

Is it free or up to each type?
If it's totally free, we could still have best practices or recommendations.

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +- arguments for those validators are valid and have sane values
same values than what?

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +- add errors for those you don’t know about;
(for unexpected authors?)

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +Next, we need to create a way for the user to input a list of authors for our validation. To achieve this, we need to implement a FormMapper that allows us to add an input field to the form where the
These sentences are full of doubt to me.
_We would like to offer a way to the user to input a list of authors that will be upon validation. To achieve this, we will implement a FormMapper that allows us to define the input field into the form where the user has defined the fields._

(If I am not correct in English nor in the programming logic, please adapt and correct).

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +The most basic one looks like the following:
I propose to change it by:

_This is a minimal example of our FormMapper:_

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +Unfortunately, because in our case authorList validator has array type, we cannot leave it like that. We will need a way to transform data from array to comma-separated string and vice versa.
It's not fate-programming, we chose what we are doing. I would like to rephrase it like this:
_In our case, authorList is an array and the validator should be set accordingly. To transform data from array to a comma-separated string and in the other way, we need to implement a DataTransformer:_

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +Next thing is to register the FormMapper as a service, so the system would know to use it. To achieve this, let's add the following lines to `fieldtypes.yml`:
Add a link to the Services documentation page, here, please.
https://doc.ezplatform.com/en/1.11/guide/service_container/

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +Also, we need to register it by editing the file `ez_field_templates.yml`:
Register it as what?
_Register the new template in the configuration_

2017-09-19 12:18 UTC, mere-teresa commented on docs/add_a_validation.md
> +
In general, I prefer to read "we will" than "we need".

2017-10-09 08:53 UTC, natanael89 commented
@mere-teresa I made the changes that you requested. Thanks a lot for your input!

2017-10-10 13:02 UTC, mere-teresa approved these changes

2017-10-11 14:00 UTC, merged