EZP-27160 EZP-27098 Update code to current LTS version
ezsystems/TweetFieldTypeBundle pull request #5
Opened 2017-04-21 07:54 UTC by natanael89

My goal was to: 
- fix any errors that prevented the code from running in the last LTS
- fix unit tests and make them pass
- change the codebase to follow PSR-2 and PHP/Symfony best practices
- remove unnecessary code

2017-04-21 08:51 UTC, bdunogier requested changes
A couple minor remarks, but overall: good job !

2017-04-21 08:51 UTC, bdunogier commented on Command/CreateTweetContentCommand.php
> +        $userService = $repository->getUserService();
Not related to this line, but there's a typo in this change's commit message: "Remove call to *depracated* method setCurrentUser".

2017-04-21 08:51 UTC, bdunogier commented on eZ/Publish/FieldType/Tweet/Type.php
> +                "Twitter user %user% is not in the approved author list",
Nitpick: single quotes :)

2017-04-21 08:51 UTC, bdunogier commented on eZ/Publish/FieldType/Tweet/Type.php
> +    private function authorApproved($author, $validatorConfiguration)
Naming: i'd change this to `isAuthorApproved` (verb).

2017-04-21 08:51 UTC, bdunogier commented on eZ/Publish/FieldType/Tweet/Type.php
> +                array('%url%' => $fieldValue->url)
Short array syntax while at it ?

2017-04-21 08:51 UTC, bdunogier commented on eZ/Publish/FieldType/Tweet/Type.php
> +            return $errors;
CS: space before return.

2017-04-21 08:51 UTC, bdunogier commented on Resources/config/fieldtypes.yml
> +        class: 'EzSystems\TweetFieldTypeBundle\eZ\Publish\FieldType\Tweet\Type'
Unless I'm mistaken, the quotes aren't necessary (see the examples from http://symfony.com/doc/current/service_container.html). I'd remove them altogether.

2017-04-21 08:53 UTC, bdunogier commented
Note that some of my comments show as outdated, as I have reviewed per commit.

For the future, the CS change on the whole repository should maybe be done first, as it made it very hard to distinguish CS changes from code changes when reviewing the PR as a whole.

2017-04-21 10:23 UTC, natanael89 commented
I made requested changes and few more :)

I agree with your comment about CS changes and I will do just that next time.

2017-04-26 08:21 UTC, bdunogier approved these changes

2017-04-26 08:23 UTC, bdunogier commented
@natanael89 can you rebase on top of master ? A typo fix ("ocurred" / "occurred") was merged yesterday that conflicts with your CS changes.

Once that is done, we can merge it.

2017-04-26 12:31 UTC, natanael89 commented
@bdunogier I rebased it, so it's ready to be merged.

2017-05-02 14:02 UTC, lolautruche approved these changes
Besides my comment about YAML loading and minor stuff, +1

2017-05-02 14:02 UTC, lolautruche commented on DependencyInjection/EzSystemsTweetFieldTypeExtension.php
> +        $config = Yaml::parse(__DIR__ . '/../Resources/config/ez_field_templates.yml');
`Yaml::parse()` must take YAML content now:

```php
$config = Yaml::parse(file_get_contents(__DIR__ . '/../Resources/config/ez_field_templates.yml'));
```

2017-05-02 14:02 UTC, lolautruche commented on Resources/views/fields/eztweet.html.twig
>  {% endblock %}
Missing empty line at end of file

2017-05-02 14:02 UTC, lolautruche commented on Resources/views/platformui/content_type/view/eztweet.html.twig
> +{% endblock %}
Missing empty line

2017-05-02 20:56 UTC, bdunogier commented
We will merge once @lolautruche's suggestions have been integrated. Thank you !

2017-05-04 07:10 UTC, natanael89 commented
Thank you for your comments @lolautruche! Your suggestions have been added.

2017-05-04 07:45 UTC, andrerom approved these changes

2017-05-04 07:52 UTC, mere-teresa commented
Thank you @natanael89 !

2017-05-04 07:53 UTC, merged